Clear observability DB
accuknox/discovery-engine pull request #398
Opened 2022-02-06 07:28 UTC by seswarrajan

2022-02-06 12:47 UTC, nyrahul requested changes

2022-02-06 12:47 UTC, nyrahul commented on scripts/observe_db_clear.sh
> +#!/bin/bash
Let's use the existing script db_clear.sh for this purpose.
db_clear.sh is also copied in the knoxautopolicy dockerfile.

2022-02-06 12:47 UTC, nyrahul commented on scripts/observe_db_clear.sh
> +grpcurl -plaintext -d "$DATA" localhost:9089 v1.observability.Observability.ClearDb
we have an existing db-clear endpoint.. lets extend the same.

2022-02-08 10:38 UTC, closed without merging

2022-02-08 10:38 UTC, seswarrajan commented
Will handle in a fresh new PR