handle stable/dev image release creation
accuknox/discovery-engine pull request #421
Opened 2022-02-24 20:08 UTC by Ankurk99

Ref: #412

2022-02-28 16:02 UTC, nyrahul requested changes

2022-02-28 16:02 UTC, nyrahul commented on k3s/README.md
> +$ cd KubeArmor/contribution/k3s
Reference to kubearmor in auto-policy-discovery??

2022-02-28 16:02 UTC, nyrahul commented on k3s/install_k3s.sh
> +# Copyright 2021 Authors of KubeArmor
```suggestion
# Copyright 2022 Authors of auto-policy-discovery
```

2022-02-28 16:02 UTC, nyrahul commented on k3s/install_k3s.sh
> +sleep 15
Can we remove the sleep and add something [like this](https://github.com/kubearmor/KubeArmor/blob/eb71e99aebc4e1df2b01ad11f62fd0a82b5933f7/.github/workflows/latest-release.yml#L46) to check if the pods are ready?

2022-02-28 16:20 UTC, Ankurk99 commented on k3s/README.md
> +$ cd KubeArmor/contribution/k3s
Oops, I copied the k8s setup from KubeArmor, will change it

2022-02-28 16:51 UTC, Ankurk99 commented on k3s/install_k3s.sh
> +sleep 15
It is waiting for k3s to start. I think we can do without it as the commands are run step-wise.

2022-03-02 04:31 UTC, nyrahul approved these changes

2022-03-02 04:31 UTC, merged