helm chart update
accuknox/discovery-engine pull request #570
Opened 2022-10-21 07:06 UTC by Nagarajan0396

2022-10-21 17:39 UTC, nyrahul approved these changes
Two minor comments. Please check and handle, otherwise all good.

2022-10-21 17:39 UTC, nyrahul commented on deployments/discovery-engine-chart/Chart.yaml
> +description: A Helm chart for DiscoveryEngine
```suggestion
description: A Helm chart for AccuKnox DiscoveryEngine

```

2022-10-21 17:39 UTC, nyrahul commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +    network-log-from: "hubble"                # db|hubble|feed-consumer
This configuration is wrong. Please check the latest config in src/conf/local-file.yaml

2022-10-21 18:00 UTC, nyrahul commented
Hey @Nagarajan0396 , thank you for working on this. Lets handle few basic comments above and this should be good to merge.

2022-10-25 04:45 UTC, Nagarajan0396 commented
Hi @nyrahul  Changes has been done.

2022-10-25 13:35 UTC, nyrahul approved these changes

2022-10-31 08:03 UTC, wazir-ahmed requested changes

2022-10-31 08:03 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +    #network-log-file: "/home/rahul/feeds.json"   # file path
```suggestion
```

2022-10-31 08:03 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +    #system-log-file: "./log.json"            # file path
```suggestion
```

2022-10-31 08:03 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +    #cluster-mgmt-url: "http://cluster-management-service.accuknox-dev-cluster-mgmt.svc.cluster.local/cm"
```suggestion
```

2022-10-31 08:03 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +    # kubearmor: "kubearmor-alerts"
```suggestion
```

2022-10-31 08:03 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +  # -----------------------------------------------
```suggestion
```

2022-10-31 08:03 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/templates/hpa.yaml
> +{{- if .Values.autoscaling.enabled }}
We don't need HPA.

2022-10-31 08:03 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/templates/ingress.yaml
> +{{- if .Values.ingress.enabled -}}
We don't need Ingress.

2022-10-31 08:03 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +  dbname: accuknox
```suggestion
```

2022-10-31 15:49 UTC, wazir-ahmed requested changes

2022-10-31 15:49 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +  url: localhost
```suggestion
  url: hubble-relay.kube-system.svc.cluster.local
  port: 80
```

2022-10-31 15:49 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +  url: localhost
```suggestion
  url: kubearmor.kube-system.svc.cluster.local

```

2022-10-31 15:49 UTC, wazir-ahmed commented on deployments/discovery-engine-chart/configmapfiles/discovery-engine/conf.yaml
> +# kubectl -n kube-system port-forward service/hubble-relay --address 0.0.0.0 --address :: 4245:80
```suggestion
```

2022-11-01 08:53 UTC, wazir-ahmed approved these changes
PR looks good to me. Thanks @Nagarajan0396 for the contribution.

2022-11-01 09:32 UTC, merged