Filter file paths for relative paths
accuknox/discovery-engine pull request #577
Opened 2022-10-31 04:18 UTC by Ankurk99

Prevent relative paths logs from being sent to the discovery engine

2022-10-31 05:44 UTC, seswarrajan approved these changes
LGTM

2022-10-31 06:25 UTC, nyrahul requested changes

2022-10-31 06:25 UTC, nyrahul commented on src/plugin/kubearmor.go
> +					continue
Add a warn log here with the complete event dump.

2022-11-01 04:36 UTC, rajaSahil requested changes

2022-11-01 04:36 UTC, rajaSahil commented on src/plugin/kubearmor.go
> +				kubearmorlog := pb.Log{
`kubearmorlog` -> `kubearmorLog`

2022-11-01 06:07 UTC, rajaSahil approved these changes

2022-11-08 03:40 UTC, seswarrajan approved these changes

2022-11-08 12:46 UTC, nyrahul approved these changes

2022-11-08 12:46 UTC, merged