Purge Old DB Entries
accuknox/discovery-engine pull request #595
Opened 2022-11-18 19:50 UTC by yasin-cs-ko-ak

- This PR contains generic config for purge old db entries for specific time. 
- It uses cron job to run the db query.
- discovery-engine currently uses MySQL and SQLite as databases.
- `accuknox-obs.db` and `accuknox-pol.db` added in `local-file.yaml` as of now.

2022-11-19 02:02 UTC, nyrahul approved these changes
LGTM 👍

2022-11-21 05:09 UTC, seswarrajan commented
Thanks @nyrahul for the approval. I will test once and will merge this PR.

2022-11-21 05:22 UTC, seswarrajan requested changes

2022-11-21 05:22 UTC, seswarrajan commented on src/libs/dbHandler.go
> +	DBMutex = &sync.Mutex{}
Why are we defining 2 mutexes. I did not see them being used anywhere else.

2022-11-21 05:22 UTC, seswarrajan commented on src/libs/dbHandler.go
> +	DBMutex = &sync.Mutex{}
We are defining DB mutex and not using it as lock for deleting the DB entries.

2022-11-21 05:25 UTC, rajaSahil commented on src/libs/dbHandler.go
> +	if cfg.GetCfgPurgeOldDBEntriesEnable() {
Why are we using two if statements for same condition?

2022-11-21 05:25 UTC, rajaSahil commented on src/libs/dbHandler.go
> +		go PurgeOldDBEntriesMySQL(types.ConfigDB{})
How are we ensuring, these go routines executes? Shouldn't be there wait() for these goroutines?

2022-11-21 05:25 UTC, rajaSahil commented on src/libs/mysqlHandler.go
> +func PurgeOldDBEntriesMySQL(cfg types.ConfigDB) error {
We are returning error, but where it is being handled? 
And since this function is called through a seperate goroutine, should we return error?

2022-11-21 05:25 UTC, rajaSahil commented on src/libs/sqliteHandler.go
> +func PurgeOldDBEntriesSQLite(cfg types.ConfigDB) error {
Same comment as above https://github.com/kubearmor/discovery-engine/pull/595#discussion_r1027590493

2022-11-21 09:03 UTC, closed without merging