Show recommended policy for new deployments
accuknox/discovery-engine pull request #652
Opened 2023-01-11 17:01 UTC by vishnusomank

- added deployment watcher to generate recommended policies when a new deployment is added

Signed-off-by: Vishnu Soman <vishnu@accuknox.com>

2023-01-12 06:42 UTC, nyrahul requested changes

2023-01-12 06:42 UTC, nyrahul commented on src/recommendpolicy/helperFunctions.go
> +		log.Error().Msg(err.Error())
return

2023-01-12 06:42 UTC, nyrahul commented on src/recommendpolicy/recommendPolicy.go
> +		log.Error().Msg(err.Error())
return

2023-01-18 13:32 UTC, nyrahul approved these changes

2023-01-18 13:32 UTC, merged

2023-01-18 13:34 UTC, seswarrajan reviewed
Please check how much CPU/mem is utilised since we are using a watcher .

2023-01-18 13:34 UTC, seswarrajan commented on src/libs/consumer.go
> +			log.Info().Msgf("Publishing policy %v", policy.Name)
Is this message necessary ?
The purpose of this message is for debug ?

2023-01-18 13:34 UTC, seswarrajan commented on src/recommendpolicy/helperFunctions.go
> +				generateHardenPolicy(event.Object.(*v1.Deployment).Name, event.Object.(*v1.Deployment).Namespace, event.Object.(*v1.Deployment).Spec.Template.Labels)
Are we extracting recommended policies based only on deployment name & labels
What if the same contains multiple containers ?? We are not getting recommended policies for containers ?