feat(license): add license feature
accuknox/discovery-engine pull request #702
Opened 2023-04-03 04:36 UTC by rajaSahil

- Add License feature
- Add protobuf for licensing

2023-04-11 09:16 UTC, rajaSahil commented on src/license/license.go
> +var publicKey = "-----BEGIN PUBLIC KEY-----\nMIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgHUc95xoPHqsuC3zLfCSHHJ9F/Gx\nlJdyBkns1wDYCLY8yX1vvZndfDP9br3dbFKOaYOYmF9e0gKcDpGItdBQe+TVX9ol\nM3S23yD/xHNKw+f88KjI0d
This is for testing purpose

2023-04-11 09:20 UTC, nyrahul requested changes

2023-04-11 09:20 UTC, nyrahul commented on src/cluster/k8sClientHandler.go
> +}
```suggestion
	return string(kubeSystem.GetUID()), nil
}
```

2023-04-11 09:20 UTC, nyrahul commented on src/license/license.go
> +var publicKey = "-----BEGIN PUBLIC KEY-----\nMIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgHUc95xoPHqsuC3zLfCSHHJ9F/Gx\nlJdyBkns1wDYCLY8yX1vvZndfDP9br3dbFKOaYOYmF9e0gKcDpGItdBQe+TVX9ol\nM3S23yD/xHNKw+f88KjI0d
I am not sure how is this public key used?

2023-04-11 09:20 UTC, nyrahul commented on src/license/license.go
> +	for {
If the license check fails, this would go in tight loop!

2023-04-12 00:02 UTC, rajaSahil commented on src/license/license.go
> +var publicKey = "-----BEGIN PUBLIC KEY-----\nMIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgHUc95xoPHqsuC3zLfCSHHJ9F/Gx\nlJdyBkns1wDYCLY8yX1vvZndfDP9br3dbFKOaYOYmF9e0gKcDpGItdBQe+TVX9ol\nM3S23yD/xHNKw+f88KjI0d
This is being used to verify signature for jwt token.

2023-04-12 00:02 UTC, rajaSahil commented on src/license/license.go
> +	for {
Have added 5 sec sleep.

2023-04-12 09:04 UTC, vishnusomank requested changes

2023-04-12 09:04 UTC, vishnusomank commented on src/license/license.go
> +	secret, err := cluster.GetSecrets(LCfg.k8sClient, "app=discovery-engine")
@rajaSahil  should we hardcode the labels for the discovery engine here? shouldn't it be configurable using the configmap?

2023-04-12 09:04 UTC, vishnusomank commented on src/license/license.go
> +	err = Tkn.validateClaims(userId)
@rajaSahil why are we calling `Tkn.validateClaims(userId)` can't we directly call `Tkn.validateUserId(userId)` ?

2023-04-12 09:04 UTC, vishnusomank commented on src/license/license.go
> +	Tkn := &Token{
since we are not exporting this variable why don't we use a smaller case?

2023-04-12 09:04 UTC, vishnusomank commented on src/cluster/k8sClientHandler.go
> +	secret, err := GetSecrets(k8sClient, "app=discovery-engine")
@rajaSahil should we hardcode the labels for the discovery engine here? shouldn't it be configurable using the configmap?

2023-04-12 09:04 UTC, vishnusomank commented on src/cluster/k8sClientHandler.go
> +			Name: "discovery-engine",
can we have this name as a constant and standardize it to something like `discovery-engine-license-key` or similar?

2023-04-12 09:04 UTC, vishnusomank commented on src/cluster/k8sClientHandler.go
> +	secrets, err := k8sClient.CoreV1().Secrets("").List(context.Background(), metav1.ListOptions{
Since we are creating this secret under 'kube-system' namespace with a predefined name can't we use `Secrets.Get` to get the secret?

2023-04-12 09:08 UTC, rajaSahil commented on src/license/license.go
> +	secret, err := cluster.GetSecrets(LCfg.k8sClient, "app=discovery-engine")
I don't think configmap is required here, since we only need a label and a name.
We can make it constant and use it from the code itself.

2023-04-12 09:09 UTC, rajaSahil commented on src/license/license.go
> +	err = Tkn.validateClaims(userId)
No, right now I have only validated userID but there are going to be other validation also.

2023-04-12 09:10 UTC, rajaSahil commented on src/cluster/k8sClientHandler.go
> +	secret, err := GetSecrets(k8sClient, "app=discovery-engine")
Same comment https://github.com/accuknox/discovery-engine/pull/702#discussion_r1163845462

2023-04-12 09:10 UTC, rajaSahil commented on src/cluster/k8sClientHandler.go
> +			Name: "discovery-engine",
Yes, I have made this a constant, will be pushing the commit.

2023-04-12 09:12 UTC, rajaSahil commented on src/cluster/k8sClientHandler.go
> +	secrets, err := k8sClient.CoreV1().Secrets("").List(context.Background(), metav1.ListOptions{
Yes, We can.
But I think using label would help us to avoid duplicacy.

2023-04-12 10:53 UTC, vishnusomank approved these changes

2023-04-12 18:07 UTC, nyrahul requested changes

2023-04-12 18:07 UTC, nyrahul commented on src/cluster/k8sClientHandler.go
> +	secrets, err := k8sClient.CoreV1().Secrets("kube-system").Get(context.Background(), name, metav1.GetOptions{})
We should not create any resources in the kube-system namespace. At best, we should keep this configurable.

2023-04-12 18:07 UTC, nyrahul commented on src/cluster/k8sClientHandler.go
> +	return secrets, nil
```suggestion
	return secrets, nil
```
`secrets` will be `nil` in case of failure anyways.

2023-04-12 18:07 UTC, nyrahul commented on src/cluster/k8sClientHandler.go
> +	err := k8sClient.CoreV1().Secrets("kube-system").Delete(context.Background(), name, metav1.DeleteOptions{})
Remove hard-coded `kube-system` namespace.

2023-04-12 18:07 UTC, nyrahul commented on src/cluster/k8sClientHandler.go
> +	kubeSystem, err := k8sClient.CoreV1().Namespaces().Get(context.Background(), "kube-system", metav1.GetOptions{})
remove hardcoded `kube-system` namespace.

2023-04-12 18:07 UTC, nyrahul commented on src/license/license.go
> +	licenseSecLabel           = "app=discover-engine"
```suggestion
	licenseSecLabel           = "app=discovery-engine"
```

2023-04-12 18:07 UTC, nyrahul commented on src/license/license.go
> +	LCfg.Lcs = l
This is already handled on line 66.
```suggestion
```

2023-04-12 18:07 UTC, nyrahul commented on src/license/license.go
> +	LCfg.Lcs = l
This assignment is already done in `ValidateLicense()`.
```suggestion
```

2023-04-12 18:07 UTC, nyrahul commented on src/license/license.go
> +}
```suggestion
func (t *Token) validateClaims(userId string) error {
	return t.validateUserId(userId)
}
```

2023-04-12 18:07 UTC, nyrahul commented on src/license/license.go
> +
```suggestion
func (t *Token) getFeatures() ([]string, error) {
	return t.claims.Features, nil
}
```

2023-04-12 18:07 UTC, nyrahul commented on src/license/license.go
> +}
```suggestion
func (cfg *LicenseConfig) checkExistingLicense() bool {
	return (cfg.Lcs != nil || cfg.Tkn != nil)
}
```

2023-04-12 18:07 UTC, nyrahul commented on src/license/license.go
> +}
```suggestion
func (cfg *LicenseConfig) removeLicenseSecretsConfig() error {
	cfg.Lcs = nil
	cfg.Tkn = nil
	return cluster.DeleteSecrets(LCfg.k8sClient, discoveryEngineSecretName)
}
```

2023-04-12 18:07 UTC, nyrahul commented on src/main.go
> +		os.Exit(1)
I  don't understand the point of spawning a go routine when that go routine would not be handled since the code is going to do os.Exit().

2023-04-12 18:07 UTC, nyrahul commented on src/server/grpcServer_test.go
>  	assert.NotNil(t, server)
```suggestion
	assert.NotNil(t, AddServers(AddLicenseServer(StartGrpcServer())))
```

2023-04-13 05:49 UTC, rajaSahil commented on src/cluster/k8sClientHandler.go
> +	secrets, err := k8sClient.CoreV1().Secrets("kube-system").Get(context.Background(), name, metav1.GetOptions{})
Sure, by default where should we create the secrets @nyrahul ?

2023-04-13 05:54 UTC, rajaSahil commented on src/license/license.go
> +	LCfg.Lcs = l
Assignment will only happen if there are no errors in ValidateLicense, but if there comes any error assignment won't happen.

2023-04-13 05:56 UTC, rajaSahil commented on src/main.go
> +		os.Exit(1)
grpc server starts on the new go routine and as soon as a license is installed we exit from the code.

2023-04-13 09:47 UTC, Ankurk99 commented on src/cluster/k8sClientHandler.go
> +	secrets, err := k8sClient.CoreV1().Secrets("kube-system").Get(context.Background(), name, metav1.GetOptions{})
accuknox-agents can be kept as the default ns

2023-04-13 18:15 UTC, nyrahul requested changes
There are few comments from my past reviews that are not handled. Or am i mistaken?

2023-04-13 18:15 UTC, nyrahul commented on src/license/license.go
> +	LCfg.Lcs = l
But the assignment was already done inside `ValidateLicense()`

2023-04-17 02:36 UTC, nyrahul requested changes

2023-04-17 02:36 UTC, nyrahul commented on src/cluster/k8sClientHandler.go
> +		log.Error().Msgf("error while getting license secrets with name: %s from kube-system namespace, error: %s", name, err.Error())
```suggestion
		log.Error().Msgf("error while getting license secrets with name: %s from %s namespace, error: %s", name, namespace, err.Error())
```

2023-04-17 07:44 UTC, rajaSahil commented
https://github.com/accuknox/discovery-engine/pull/702#discussion_r1165791805 But assignment only happens if ValidateLicense() doesn't throw any error.

2023-04-18 08:30 UTC, nyrahul approved these changes

2023-04-18 08:58 UTC, merged