fix(summary): exclude `container_id` from `system_summary` table
accuknox/discovery-engine pull request #713
Opened 2023-04-21 17:14 UTC by yasin-cs-ko-ak

## Issue:
Repeated entries in `system_summary `table due to different `container_id` when pod restarts.

## Description:
Every time a pod restarts, it creates a new `container_id.` This results in repeated entries in the `system_summary` table for the same pod and container, causing issues with data analysis when we are using karmor summary in CLI.

## Fix:
To prevent repeated entries in the `system_summary` table, this PR exclude the `container_id` field from the `upsertSysSummarySQL` function. Instead, the function will now use the `podname` field to check for existing entries and update them accordingly. This will ensure that only one entry exists in the table for each unique pod, regardless of how many times the container is restarted.

2023-04-24 05:51 UTC, seswarrajan requested changes
Also remove ContainerID from types/observability.go Line: 105

2023-04-24 06:01 UTC, yasin-cs-ko-ak commented
> Also remove ContainerID from types/observability.go Line: 105

if we remove the type from there, container_id will be completely removed from the db after that we can't test anything. we are only excluding the container_id.

2023-04-24 11:31 UTC, vishnusomank commented on src/libs/dbHandler.go
> +	sort.Strings(sortedLabels)
@yasin-cs-ko-ak  What is this code doing?

2023-04-25 06:06 UTC, yasin-cs-ko-ak commented
Before sorting the labels

![before-labels](https://user-images.githubusercontent.com/92008211/234188272-e1be4435-468f-445f-a5a5-79c02b34d40f.png)

After sorting the labels

![after-labels](https://user-images.githubusercontent.com/92008211/234188330-04a3ee4d-f440-46e6-b12f-858455060f6d.png)

cc: @vishnusomank

2023-04-25 07:33 UTC, yasin-cs-ko-ak commented
**Before this fix:**

![before-fix](https://user-images.githubusercontent.com/92008211/234205905-f2e5de78-d6b1-47ae-85f5-7b5f6178e59d.png)

**After this fix:** (there is no repeated entries)

![after-fix](https://user-images.githubusercontent.com/92008211/234205984-1e33b9a6-1cfb-40c5-a5fb-54add072e99a.png)

cc: @vishnusomank

2023-04-25 07:35 UTC, vishnusomank approved these changes

2023-04-25 07:43 UTC, nyrahul approved these changes

2023-04-25 08:27 UTC, seswarrajan approved these changes
LGTM

2023-04-25 08:29 UTC, seswarrajan commented
The reason for removing container_id from system_summary table is that to avoid repetitive logs. Do we not need the same for observability as well. We can remove container_id in summary from being sent to DEO.

@nyrahul @yasin-cs-ko-ak @vishnusomank @wazir-ahmed @AmanKumar2696  WDYT ?

2023-04-25 09:49 UTC, nyrahul commented
What is the purpose of observability table vs system summary table? @seswarrajan

2023-04-25 11:04 UTC, seswarrajan commented
> What is the purpose of observability table vs system summary table? @seswarrajan

We do not have separate observability table @nyrahul 
What i meant to mention is that can we disable ContainerID field from being sent to DEO ?

2023-04-26 04:13 UTC, AmanKumar2696 commented
> The reason for removing container_id from system_summary table is that to avoid repetitive logs. Do we not need the same for observability as well. We can remove container_id in summary from being sent to DEO.
> 
> @nyrahul @yasin-cs-ko-ak @vishnusomank @wazir-ahmed @AmanKumar2696 WDYT ?

In App Behaviour, we're not using ```container_id``` for any searching/filtering. Removing it should not affect any existing APIs.

2023-04-27 04:50 UTC, yasin-cs-ko-ak commented
We are only removing `container_id` from upsert query. So we can resolve this issue with minimal code changes.

2023-05-02 07:40 UTC, merged