fix(observability): fix write to db isssue for observability
accuknox/discovery-engine pull request #765
Opened 2023-07-04 22:46 UTC by rajaSahil

**Purpose of PR?**:

- Fix concurrent write issue which was happening because of using lock in a different goroutine. 
- Fixes write to db for karmor summary

*NOTE*
- There is another issue with protobuf which is causing DE to panic because of invalid go types.

**Checklist:**
- [x] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-07-05 06:08 UTC, seswarrajan requested changes

2023-07-05 06:08 UTC, seswarrajan commented on src/observability/publisher.go
> +		var ProcessSystemSummaryWg sync.WaitGroup
```suggestion
		ProcessSystemSummaryWg := sync.WaitGroup{}
```

2023-07-05 09:53 UTC, achrefbensaad approved these changes
LGTM

2023-07-05 09:57 UTC, stefin9898 commented on src/observability/publisher.go
> +		ProcessSystemSummaryWg.Wait()
We can remove the entire ProcessSystemSummaryWg by removing the call to `UpsertSummaryCronJob` as a goroutinr

2023-07-05 10:10 UTC, rajaSahil commented on src/observability/publisher.go
> +		ProcessSystemSummaryWg.Wait()
I think it will have some performance implications, let's use go routines for this.

2023-07-05 10:12 UTC, seswarrajan commented
One more suggestion. Instead of using wg wait and sync, why not write to DB one by one, in line 50, after Publish. We do have a common handle for DB and we are not going to open a new handle every time while we write to DB. 

Will that work ?

2023-07-05 10:12 UTC, stefin9898 commented on src/observability/publisher.go
> +		ProcessSystemSummaryWg.Wait()
Since it is waiting at `ProcessSystemSummaryWg.Wait()` then why should there be a goroutine?

2023-07-05 10:17 UTC, stefin9898 commented
Yes @seswarrajan that make sense! We can just iterate the tempSummarizerMap once and publish / write to db if the flags are enabled for the same

2023-07-05 10:20 UTC, rajaSahil commented on src/observability/publisher.go
> +		ProcessSystemSummaryWg.Wait()
What I  was thinking of is to spawn two go routines for both the task, but I haven't tried to implement it. I will be trying it, so let's have it for now .

2023-07-05 10:24 UTC, rajaSahil commented
> One more suggestion. Instead of using wg wait and sync, why not write to DB one by one, in line 50, after Publish. We do have a common handle for DB and we are not going to open a new handle every time while we write to DB.
> 
> Will that work ?
> 
> Since the logs/summary data is aggreagted, we will have less data and writing to DB in loop individually will not cost much. Please correct me if i am wrong.

No, having seperate configs make sense to me!

2023-07-05 10:27 UTC, stefin9898 commented
> No, having seperate configs make sense to me!

Yes, it will be having separate configs. I believe @seswarrajan meant to iterate the  tempSummarizerMap once. right?

2023-07-05 10:28 UTC, seswarrajan commented
> > One more suggestion. Instead of using wg wait and sync, why not write to DB one by one, in line 50, after Publish. We do have a common handle for DB and we are not going to open a new handle every time while we write to DB.
> > Will that work ?
> > Since the logs/summary data is aggreagted, we will have less data and writing to DB in loop individually will not cost much. Please correct me if i am wrong.
> 
> No, having seperate configs make sense to me!

@rajaSahil The config still remains untouched. We will have separate configs. But, we need to call write to db after Publish. For each log. That write will fall inside the condition check.

2023-07-05 10:31 UTC, rajaSahil commented
@seswarrajan Unable to get you. Why not we spawn two different goroutines and have it processed at the same time?

2023-07-06 04:21 UTC, vishnusomank commented on src/observability/publisher.go
> +	aggregateSummaryMap(tempSummarizerMap)
Do we really need to aggregate and store in the DB? IMO we should keep the raw data in DB and use agg before publishing it to SaaS? WDY @rajaSahil @seswarrajan

2023-07-06 05:03 UTC, rajaSahil commented on src/observability/publisher.go
> +	aggregateSummaryMap(tempSummarizerMap)
We are anyway aggregating  the data before pushing to SAAS, why can't we store aggregated result in the DB? Is it going to create any issues? We anyway aggregate all the file data for karmor summary, so we can do 1st level of aggregation over here which can increase performance for karmor summary also.

2023-07-06 05:09 UTC, vishnusomank commented on src/observability/publisher.go
> +	aggregateSummaryMap(tempSummarizerMap)
It is not going to create any issues. And the agg is false by default in karmor summary right? That is why I suggested to keep it raw.

2023-07-06 14:04 UTC, Ankurk99 approved these changes
LGTM!

2023-07-07 04:35 UTC, seswarrajan approved these changes

2023-07-07 04:35 UTC, merged